from app.core.errors import InvalidTransition

DETECTED = "DETECTED"
ANALYZING = "ANALYZING"
RECOMMENDED = "RECOMMENDED"
POLICY_CHECK = "POLICY_CHECK"
WAITING = "WAITING"
APPROVED = "APPROVED"
PROCESSING = "PROCESSING"
CONTACTED = "CONTACTED"
PAYMENT_PENDING = "PAYMENT_PENDING"
RECOVERED = "RECOVERED"
FAILED = "FAILED"
STOPPED = "STOPPED"
ESCALATED = "ESCALATED"
PROMISE_TO_PAY = "PROMISE_TO_PAY"
BROKEN_PROMISE = "BROKEN_PROMISE"
EXPIRED = "EXPIRED"

TERMINAL = {RECOVERED, STOPPED, EXPIRED}

TRANSITIONS = {
    DETECTED: {ANALYZING, STOPPED, ESCALATED},
    ANALYZING: {RECOMMENDED, ESCALATED, STOPPED, FAILED},
    RECOMMENDED: {POLICY_CHECK, ESCALATED, STOPPED},
    POLICY_CHECK: {APPROVED, WAITING, ESCALATED, STOPPED, PROMISE_TO_PAY},
    WAITING: {ANALYZING, POLICY_CHECK, APPROVED, ESCALATED, STOPPED, EXPIRED, PROMISE_TO_PAY},
    APPROVED: {PROCESSING, WAITING, ESCALATED, STOPPED, PROMISE_TO_PAY},
    PROCESSING: {CONTACTED, PAYMENT_PENDING, FAILED, ESCALATED, STOPPED, RECOVERED, PROMISE_TO_PAY},
    CONTACTED: {PAYMENT_PENDING, PROMISE_TO_PAY, RECOVERED, FAILED, WAITING, ESCALATED, STOPPED},
    PAYMENT_PENDING: {RECOVERED, FAILED, PROMISE_TO_PAY, WAITING, ESCALATED, STOPPED, EXPIRED},
    PROMISE_TO_PAY: {RECOVERED, BROKEN_PROMISE, WAITING, ESCALATED, STOPPED, EXPIRED},
    BROKEN_PROMISE: {ANALYZING, WAITING, ESCALATED, STOPPED, RECOVERED},
    FAILED: {ANALYZING, WAITING, ESCALATED, STOPPED, EXPIRED},
    ESCALATED: {RECOVERED, STOPPED, WAITING},
    RECOVERED: set(),
    STOPPED: set(),
    EXPIRED: set(),
}


def can_transition(current: str, target: str) -> bool:
    return target in TRANSITIONS.get(current, set())


def transition(current: str, target: str) -> str:
    if current == target:
        return target
    if not can_transition(current, target):
        raise InvalidTransition(
            f"Recovery case cannot move from {current} to {target}",
            {"from": current, "to": target, "allowed": sorted(TRANSITIONS.get(current, set()))},
        )
    return target


def is_terminal(state: str) -> bool:
    return state in TERMINAL


ACTIVE = {
    DETECTED,
    ANALYZING,
    RECOMMENDED,
    POLICY_CHECK,
    WAITING,
    APPROVED,
    PROCESSING,
    CONTACTED,
    PAYMENT_PENDING,
    PROMISE_TO_PAY,
    BROKEN_PROMISE,
    FAILED,
}
