PAYMENT_RETRY = "PAYMENT_RETRY"
PAYMENT_LINK = "PAYMENT_LINK"
EMAIL = "EMAIL"
VOICE_AI = "VOICE_AI"
SMS = "SMS"
IN_APP = "IN_APP"
HUMAN_ESCALATION = "HUMAN_ESCALATION"

ACTIONS = [PAYMENT_RETRY, PAYMENT_LINK, EMAIL, VOICE_AI, SMS, IN_APP, HUMAN_ESCALATION]
CHANNELS = [EMAIL, VOICE_AI, SMS, PAYMENT_LINK, IN_APP, HUMAN_ESCALATION]
CONTACT_CHANNELS = [EMAIL, VOICE_AI, SMS, IN_APP]

PRIORITY_CRITICAL = "CRITICAL"
PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"
PRIORITIES = [PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW]
PRIORITY_ORDER = {name: index for index, name in enumerate(PRIORITIES)}

RISK_CRITICAL = "CRITICAL"
RISK_HIGH = "HIGH"
RISK_MEDIUM = "MEDIUM"
RISK_LOW = "LOW"

FAILURE_TYPES = [
    "TEMPORARY_BANK_TIMEOUT",
    "INSUFFICIENT_FUNDS",
    "CARD_EXPIRED",
    "GATEWAY_FAILURE",
    "AUTHENTICATION_FAILURE",
    "RECURRING_MANDATE_FAILURE",
    "CHECKOUT_ABANDONED",
    "OVERDUE_INVOICE",
]

FAILURE_LABELS = {
    "TEMPORARY_BANK_TIMEOUT": "Temporary bank timeout",
    "INSUFFICIENT_FUNDS": "Insufficient funds",
    "CARD_EXPIRED": "Expired card",
    "GATEWAY_FAILURE": "Payment gateway failure",
    "AUTHENTICATION_FAILURE": "Authentication failure",
    "RECURRING_MANDATE_FAILURE": "Failed subscription renewal",
    "CHECKOUT_ABANDONED": "Checkout abandonment",
    "OVERDUE_INVOICE": "Overdue payment",
}

PAYMENT_METHODS = ["card", "upi", "netbanking", "wallet", "emandate"]

PROMISE_ACTIVE = "ACTIVE"
PROMISE_FULFILLED = "FULFILLED"
PROMISE_BROKEN = "BROKEN"
PROMISE_EXPIRED = "EXPIRED"
PROMISE_CANCELLED = "CANCELLED"

GATEWAY_HEALTHY = "HEALTHY"
GATEWAY_DEGRADED = "DEGRADED"
GATEWAY_UNAVAILABLE = "UNAVAILABLE"

EVENT_PAYMENT_DETECTED = "PAYMENT_DETECTED"
EVENT_RISK_SCORED = "RISK_SCORED"
EVENT_ML_PREDICTION = "ML_PREDICTION"
EVENT_AI_DIAGNOSIS = "AI_DIAGNOSIS"
EVENT_AI_RECOMMENDATION = "AI_RECOMMENDATION"
EVENT_POLICY_CHECKED = "POLICY_CHECKED"
EVENT_POLICY_BLOCKED = "POLICY_BLOCKED"
EVENT_GUARDRAIL_CHECKED = "GUARDRAIL_CHECKED"
EVENT_GUARDRAIL_BLOCKED = "GUARDRAIL_BLOCKED"
EVENT_CHANNEL_SELECTED = "CHANNEL_SELECTED"
EVENT_CONTACT_STARTED = "CONTACT_STARTED"
EVENT_CONTACT_COMPLETED = "CONTACT_COMPLETED"
EVENT_PAYMENT_LINK_CREATED = "PAYMENT_LINK_CREATED"
EVENT_PAYMENT_RETRIED = "PAYMENT_RETRIED"
EVENT_PAYMENT_RECOVERED = "PAYMENT_RECOVERED"
EVENT_PROMISE_CREATED = "PROMISE_TO_PAY_CREATED"
EVENT_PROMISE_FULFILLED = "PROMISE_TO_PAY_FULFILLED"
EVENT_PROMISE_BROKEN = "PROMISE_TO_PAY_BROKEN"
EVENT_QUIET_HOURS_BLOCKED = "QUIET_HOURS_BLOCKED"
EVENT_ESCALATED = "ESCALATED"
EVENT_CASE_STOPPED = "CASE_STOPPED"
EVENT_STATE_CHANGED = "STATE_CHANGED"
EVENT_GATEWAY_FALLBACK = "GATEWAY_FALLBACK"
EVENT_VOICE_STARTED = "VOICE_CALL_STARTED"
EVENT_VOICE_TURN = "VOICE_TURN"
EVENT_VOICE_ENDED = "VOICE_CALL_ENDED"
EVENT_IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
EVENT_AI_FALLBACK = "AI_FALLBACK"

ACTOR_AGENT = "revora_agent"
ACTOR_POLICY = "policy_engine"
ACTOR_GUARDRAIL = "guardrail_engine"
ACTOR_ML = "ml_predictor"
ACTOR_AI = "ai_decision_engine"
ACTOR_DETECTOR = "revenue_detector"
ACTOR_EXECUTOR = "recovery_executor"
ACTOR_VOICE = "voice_agent"
ACTOR_GATEWAY = "gateway_pool"
ACTOR_WEBHOOK = "razorpay_webhook"
ACTOR_OPERATOR = "operator"

ATTEMPT_PENDING = "PENDING"
ATTEMPT_IN_FLIGHT = "IN_FLIGHT"
ATTEMPT_SUCCEEDED = "SUCCEEDED"
ATTEMPT_FAILED = "FAILED"
ATTEMPT_BLOCKED = "BLOCKED"
ATTEMPT_OPEN = {ATTEMPT_PENDING, ATTEMPT_IN_FLIGHT}

DIRECTION_OUTBOUND = "outbound"
DIRECTION_INBOUND = "inbound"

COMMUNICATION_SENT = "SENT"
COMMUNICATION_FAILED = "FAILED"

ESCALATION_OPEN = "OPEN"
ESCALATION_RESOLVED = "RESOLVED"
